import DS from 'ember-data';

export default DS.Model.extend({
  login: DS.attr('string'),
  avatar_url: DS.attr('string'),
  gravatar_id: DS.attr('number'),
  url: DS.attr('string'),
  html_url: DS.attr('string'),
  followers_url: DS.attr('string'),
  following_url: DS.attr('string'),
  gists_url: DS.attr('string'),
  starred_url: DS.attr('string'),
  subscriptions_url: DS.attr('string'),
  organizations_url: DS.attr('string'),
  repos_url: DS.attr('string'),
  events_url: DS.attr('string'),
  received_events_url: DS.attr('string'),
  type: DS.attr('string'),
  site_admin: DS.attr('boolean'),
  name: DS.attr('string'),
  company: DS.attr('string'),
  blog: DS.attr('string'),
  location: DS.attr('string'),
  email: DS.attr('string'),
  hireable: DS.attr('boolean'),
  bio: DS.attr('string'),
  public_repos: DS.attr('number'),
  public_gists: DS.attr('number'),
  followers: DS.attr('number'),
  following: DS.attr('number'),
  created_at: DS.attr('date'),
  updated_at: DS.attr('date')
});
